### ISSUE TITLE
Tags

### ISSUE THREAD

**Issue by micwoj92** [CHEF-KOCH/Chromium-hardening#15]
Hello, why is "basilisk" in tags? It doesnt have that much in common with current firefox. I would understand if there was a part about "legacy" firefox based browses but it isnt so I dont understand why that tag is here.

**Comment by CHEF-KOCH** [comment]
Do I really have to explain myself now about my decisions and about my tags ...

That is really a new low ....

**Comment by micwoj92** [comment]
Well It seemed like unnecessary hence I asked... Especially knowing how PM/balisisk folks think about chrome/new firefox.
