### ISSUE TITLE
Grammatical errors on the project description

### ISSUE THREAD

**Issue by Dyras** [CHEF-KOCH/Chromium-hardening#2]
Greetings!

The [project description](https://github.com/CHEF-KOCH/Chromium-hardening) says this:
"Hardens Chromium and it's settings in the name of security"
"Hardens Chromium and it's settings in the name of 'security' :suspect:"

In both cases, it's supposed to say "its" instead of "it's"

Great project by the way! I love the anti-Chromium propaganda people seem to spread, yet they completely ignore the issues with Firefox

**Comment by CHEF-KOCH** [comment]
Thanks for the correction, ideas and help is always welcome.
